name: Update tags.json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # First day of every month

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install project and deps
        run: pip install -e .

      - name: Run newtags.py
        run: python newtags.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Cron: Update tags.json"
          file_pattern: '*.json'
          skip_fetch: false
