name: publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install `build` dependency
        run: python -m pip install -U build

      - name: Build library
        run: python -m build

      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
